feat: Реализовать функционал Items1
dzrgln/shareIt-app pull request #1
Opened 2022-07-28 15:25 UTC by dzrgln

2022-07-31 16:25 UTC, kukolev requested changes

2022-07-31 16:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/ShareItApplication.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-07-31 16:25 UTC, kukolev commented on src/test/java/ru/yandex/practicum/ShareItApplicationTests.java
> +	@Test
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-07-31 16:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/exceptions/ErrorResponse.java
> +public class ErrorResponse {
Тут лучше добавить аннотацию `@Getter`. Тогда не нужно будет писать геттер.

2022-07-31 16:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/item/Item.java
> +
Это лишняя пустая строка. Мелочь, но по моему лучше удалить. Так код будет смотреться лучше.

2022-07-31 16:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/item/storage/InMemoryItemStorage.java
> +//        if (userid == 0) {
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-07-31 16:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/item/storage/InMemoryItemStorage.java
> +            System.out.println("Inside if");
Логирование нужно делать с помощью логгера, а не просто выводить данные в консоль. Это важно, т.к. тогда можно будет управлять настройками логирования. Нужно поправить.

2022-07-31 16:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/item/storage/InMemoryItemStorage.java
> +            System.out.println("After getUserById");
Логирование нужно делать с помощью логгера, а не просто выводить данные в консоль. Это важно, т.к. тогда можно будет управлять настройками логирования. Нужно поправить.

2022-07-31 16:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/item/storage/InMemoryItemStorage.java
> +        if (items.containsKey(itemId)) {
Валидации лучше вынести в отдельный приватный метод. Так код будет понятней.

В отдельном методе можно будет прописать эти проверки подряд, тогда не нужно будет делать много встроенных if. Примерно так это может выглядеть:

```
if (...) {
    throw ObjectNotFoundException(...)
}
if (...) {
    throw ValidationException(...)
}
if (...) {
    throw ObjectNotFoundException(...)
}
```

2022-07-31 16:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/item/storage/InMemoryItemStorage.java
> +                if (item.isAvailable()) {
Это условие можно объединить со следующим. Тогда вложенность будет меньше и код будет восприниматься проще.

2022-07-31 16:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/user/storage/InMemoryUserStorage.java
> +        if (id == 0) {
Валидации лучше вынести в отдельный приватный метод. Так код будет понятней.

2022-07-31 20:09 UTC, dzrgln commented on src/main/java/ru/yandex/practicum/item/storage/InMemoryItemStorage.java
> +            System.out.println("Inside if");
Спасибо за замечание. 
Это не логгирование, а осталось от дебага. Логгирование в контролерах. 
Лишние строки просто удалю

2022-08-01 16:38 UTC, kukolev requested changes

2022-08-01 16:38 UTC, kukolev commented on src/main/java/ru/yandex/practicum/exceptions/ErrorResponse.java
> +
Это лишняя пустая строка. Лучше удалить, чтобы код был единообразным. Так код будет смотреться лучше.

2022-08-02 07:09 UTC, kukolev approved these changes

2023-03-02 18:27 UTC, merged